[package]
name = "rust-secp256k1"
version = "0.1.0"
authors = ["Kirill Fomichev <fanatid@ya.ru>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
secp256k1-sys = "0.4.0"

[profile.release]
lto = true
codegen-units = 1
